# workflow 의 이름
name: issues labeler

# 트리거될 이벤트 설정
on:
  issue_comment:
    types: [created]

# 트리거되었을 때 실행될 job 작성
jobs:
  labeler:
    runs-on: ubuntu-latest
    # 리파지토리에 대한 권한 설정

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
