# workflow 의 이름
name: issues labeler

# 트리거될 이벤트 설정
on:
  issue_comment:
    types: [created]

# 트리거되었을 때 실행될 job 작성
jobs:
  issue_commented:
    # This job only runs for issue comments
    name: apply-label
    runs-on: ubuntu-latest
    steps:
      - name: Add deploy comment # https://stackoverflow.com/questions/58066966/commenting-a-pull-request-in-a-github-action
        if: github.event.comment.user == 'ryan-dia'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['철원']
            })
